services:
  - type: web
    name: world-cup-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install --include=dev --no-audit && VITE_API_URL=/api npm run build && cd ../backend && npm install --include=dev && npm run build
    startCommand: cd backend && npm install --include=dev --no-audit && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: world-cup-db
          property: connectionString
      - key: IMPORT_SECRET
        generateValue: true
      - key: PORT
        value: 5000

databases:
  - name: world-cup-db
    plan: free
    region: oregon
